"""empty message

Revision ID: 74341cddb890
Revises: 
Create Date: 2022-01-25 16:35:22.218466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74341cddb890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('artist', sa.String(length=30), nullable=False),
    sa.Column('genre', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('genre', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trap')
    op.drop_table('rap')
    op.drop_table('pop')
    op.drop_table('artist')
    op.drop_table('all_musics')
    # ### end Alembic commands ###
